# Generated by Django 3.1.5 on 2021-02-01 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sneaker',
            options={'ordering': ['-id'], 'verbose_name': 'Кроссовоки', 'verbose_name_plural': 'Кроссовоки'},
        ),
        migrations.AddField(
            model_name='sneaker',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
