# Generated by Django 3.1.5 on 2021-02-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210201_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('sneaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.sneaker', verbose_name='Кроссовки')),
            ],
        ),
    ]
