# Generated by Django 3.1.5 on 2021-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Размер'),
        ),
    ]
