# Generated by Django 3.1.5 on 2021-02-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210201_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Размер'),
        ),
    ]
