# Generated by Django 3.1.5 on 2021-02-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210201_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sneaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sneaker', verbose_name='Кроссовки'),
        ),
    ]
