# Generated by Django 3.1.5 on 2021-02-05 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210205_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_sneaker',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего кроссовок'),
        ),
        migrations.AlterField(
            model_name='sneakerincart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='sneakerincart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
