# Generated by Django 3.1.5 on 2021-02-05 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_auto_20210205_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakerincart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покапатель'),
        ),
        migrations.AlterField(
            model_name='sneakerincart',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='sneakerincart',
            name='sneaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.sneaker', verbose_name='Кроссовки'),
        ),
    ]
