# Generated by Django 3.1.5 on 2021-02-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210205_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerincart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
