# Generated by Django 3.1.5 on 2021-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210205_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
    ]
