# Generated by Django 3.1.5 on 2021-02-16 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210216_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена со скидкой'),
        ),
    ]
