# Generated by Django 3.1.5 on 2021-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210222_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites_sneakers',
            field=models.ManyToManyField(null=True, to='store.Sneaker', verbose_name='Избранные кроссоки'),
        ),
    ]
