# Generated by Django 3.1.5 on 2021-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210222_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites_sneakers',
            field=models.ManyToManyField(blank=True, null=True, to='store.Sneaker', verbose_name='Избранные кроссоки'),
        ),
    ]
