# Generated by Django 3.1.5 on 2021-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210222_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites_sneakers',
            field=models.ManyToManyField(blank=True, to='store.Sneaker', verbose_name='Избранные кроссоки'),
        ),
    ]
