# Generated by Django 3.1.5 on 2021-02-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210227_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerincart',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='Размер'),
            preserve_default=False,
        ),
    ]
