# Generated by Django 3.1.5 on 2021-02-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210227_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerincart',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.size', verbose_name='Размер'),
        ),
    ]
